version: '3.9'
services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # - ./backups:/backups
      - ./database.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admintasystem
      MYSQL_DATABASE: TASystem
      MYSQL_PASSWORD: admintasystem
      MYSQL_ROOT_HOST: '%'
    networks:
      - sanetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    networks:
      - sanetwork

  tasystem-ui:
    build:
      context: .
    environment:
      - NEXT_BACKEND_URL=http://tasystem-server:3001
    ports:
      - '3000:3000'
    container_name: TASystem-ui
    stdin_open: true
    volumes:
      - .:/usr/src/app/TASystem
      - /usr/src/app/TASystem/node_modules
    depends_on:
      - tasystem-server
    networks:
      - sanetwork

  tasystem-server:
    build:
      context: ./backend
      # args:
      #   REACT_APP_ENV: ${REACT_APP_ENV}
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=admintasystem
      - DB_NAME=TASystem
    ports:
      - '3001:3001'
    container_name: TASystem-server
    working_dir: /usr/src/app/TASystem/backend
    stdin_open: true
    volumes:
      - ./backend:/usr/src/app/TASystem/backend
      - /usr/src/app/TASystem/backend/node_modules
    depends_on:
      - db

    restart: on-failure
    #command: ['/bin/sh', '-c', './wait.sh', '-t', '0', 'db:3306', '--', 'yarn dev']
    command:
      [
        '/usr/src/app/TASystem/backend/wait.sh',
        '-t',
        '0',
        'db:3306',
        '--',
        'yarn',
        'start',
      ]
    # command: ['sh', '-c', './test.sh']
    networks:
      - sanetwork
networks:
  sanetwork:
    driver: bridge
